#!/bin/sh

cp ../../.node-red/projects/node_red/shellies2/Kellertreppe_Licht_Treppenlicht.js Treppenlicht.js
cp ../../.node-red/projects/node_red/shellies2/Kellertreppe_Licht_ShellyBlu.js ShellyBlu.js
cp ../../.node-red/projects/node_red/shellies2/Heizung_Stromzähler_SumPhases.js SumPhases.js
cp ../../.node-red/projects/node_red/shellies2/Kellertreppe_Licht_KeepAlive.js KeepAlive.js
cp ../../.node-red/projects/node_red/shellies2/Heizung_Stromzähler_GetTemp.js Stromzaehler_GetTemp.js
cp ../../.node-red/projects/node_red/shellies2/Heizung_Stromzähler_Voltages.js Stromzaehler_Voltages.js
cp ../../.node-red/projects/node_red/shellies2/Wohnzimmer_TV_Licht_DualLed.js DualLed.js
cp ../../.node-red/projects/node_red/shellies2/PV_Speicher_Inverter.js Inverter.js

cp ../../.node-red/projects/node_red/shellies2/Eichenau_Roll_Ter_Mst_Master.js D2D_RolladenMaseter.js
