#!/bin/sh

cp ../../.node-red/projects/node_red/shellies2/Kellertreppe_Licht_Treppenlicht.js Treppenlicht.js
cp ../../.node-red/projects/node_red/shellies2/Kellertreppe_Licht_ShellyBlu.js ShellyBlu.js
cp ../../.node-red/projects/node_red/shellies2/shellypro3em_SumPhases.js SumPhases.js
cp ../../.node-red/projects/node_red/shellies2/Verteilung_KeepAlive.js KeepAlive.js
